version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cine_api
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/code
    command: >
      sh -c "python create_db.py && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  db:
    image: postgres:15
    container_name: cine_db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: cine_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  db_data:
